/* This file should define __BYTE_ORDER as appropriate for the machine
   in question.  See string/endian.h for how to define it.

   If only the stub bytesex.h applies to a particular configuration,
   bytesex.h is generated by running a program on the host machine.
   So if cross-compiling to a machine with a different byte order,
   the bytesex.h file for that machine must exist.  */

#error Machine byte order unknown.
