ifeq ($(subdir),string)
sysdep_routines += strlen strlen-vx strlen-c \
		   strnlen strnlen-vx strnlen-c \
		   strcpy strcpy-vx \
		   stpcpy stpcpy-vx stpcpy-c \
		   strncpy strncpy-vx \
		   stpncpy stpncpy-vx stpncpy-c \
		   strcat strcat-vx strcat-c
endif

ifeq ($(subdir),wcsmbs)
sysdep_routines += wcslen wcslen-vx wcslen-c \
		   wcsnlen wcsnlen-vx wcsnlen-c \
		   wcscpy wcscpy-vx wcscpy-c \
		   wcpcpy wcpcpy-vx wcpcpy-c \
		   wcsncpy wcsncpy-vx wcsncpy-c \
		   wcpncpy wcpncpy-vx wcpncpy-c \
		   wcscat wcscat-vx wcscat-c
endif
