/* This file was generated by errlist-compat.awk; DO NOT EDIT!  */

#include <shlib-compat.h>

#if SHLIB_COMPAT (libc, GLIBC_2_0, GLIBC_2_1)
# include <bits/wordsize.h>
extern const char *const __sys_errlist_GLIBC_2_0[];
const int __sys_nerr_GLIBC_2_0 = 123;
strong_alias (_sys_errlist_internal, __sys_errlist_GLIBC_2_0)
declare_symbol (__sys_errlist_GLIBC_2_0, object, __WORDSIZE/8*123)
compat_symbol (libc, __sys_errlist_GLIBC_2_0, sys_errlist, GLIBC_2_0);
compat_symbol (libc, __sys_nerr_GLIBC_2_0, sys_nerr, GLIBC_2_0);
extern const char *const ___sys_errlist_GLIBC_2_0[];
extern const int __sys_nerr_GLIBC_2_0;
strong_alias (__sys_errlist_GLIBC_2_0, ___sys_errlist_GLIBC_2_0)
strong_alias (__sys_nerr_GLIBC_2_0, ___sys_nerr_GLIBC_2_0)
compat_symbol (libc, ___sys_errlist_GLIBC_2_0, _sys_errlist, GLIBC_2_0);
compat_symbol (libc, ___sys_nerr_GLIBC_2_0, _sys_nerr, GLIBC_2_0);
#endif

#if SHLIB_COMPAT (libc, GLIBC_2_1, GLIBC_2_3)
# include <bits/wordsize.h>
extern const char *const __sys_errlist_GLIBC_2_1[];
const int __sys_nerr_GLIBC_2_1 = 125;
strong_alias (_sys_errlist_internal, __sys_errlist_GLIBC_2_1)
declare_symbol (__sys_errlist_GLIBC_2_1, object, __WORDSIZE/8*125)
compat_symbol (libc, __sys_errlist_GLIBC_2_1, sys_errlist, GLIBC_2_1);
compat_symbol (libc, __sys_nerr_GLIBC_2_1, sys_nerr, GLIBC_2_1);
extern const char *const ___sys_errlist_GLIBC_2_1[];
extern const int __sys_nerr_GLIBC_2_1;
strong_alias (__sys_errlist_GLIBC_2_1, ___sys_errlist_GLIBC_2_1)
strong_alias (__sys_nerr_GLIBC_2_1, ___sys_nerr_GLIBC_2_1)
compat_symbol (libc, ___sys_errlist_GLIBC_2_1, _sys_errlist, GLIBC_2_1);
compat_symbol (libc, ___sys_nerr_GLIBC_2_1, _sys_nerr, GLIBC_2_1);
#endif

extern const char *const __sys_errlist_internal[];
extern const int __sys_nerr_internal;
strong_alias (_sys_errlist_internal, __sys_errlist_internal)
strong_alias (_sys_nerr_internal, __sys_nerr_internal)
versioned_symbol (libc, _sys_errlist_internal, sys_errlist, GLIBC_2_3);
versioned_symbol (libc, __sys_errlist_internal, _sys_errlist, GLIBC_2_3);
versioned_symbol (libc, _sys_nerr_internal, sys_nerr, GLIBC_2_3);
versioned_symbol (libc, __sys_nerr_internal, _sys_nerr, GLIBC_2_3);
