ifeq ($(subdir),math)
sysdep_routines += s_isnan-power7 s_isnan-power6x s_isnan-power6 \
		   s_isnan-power5 s_isnan-ppc64

libm-sysdep_routines += s_isnan-power7 s_isnan-power6x s_isnan-power6 \
			s_isnan-power5 s_isnan-ppc64 s_llround-power6x \
			s_llround-power5+ s_llround-ppc64 s_ceil-power5+ \
			s_ceil-ppc64 s_ceilf-power5+ s_ceilf-ppc64
endif
