\input texinfo                  @c -*- Texinfo -*-
@comment %**start of header (This is for running Texinfo on a region.)
@setfilename libc.info
@settitle The GNU C Library
@setchapternewpage odd

@comment Tell install-info what to do.
@dircategory GNU libraries
@direntry
* Libc: (libc).                 C library.
@end direntry

@c This tells texinfo.tex to use the real section titles in xrefs in
@c place of the node name, when no section title is explicitly given.
@set xref-automatic-section-title
@c @smallbook
@comment %**end of header (This is for running Texinfo on a region.)

@c sold 0.06/1.09, print run out 21may96
@set EDITION 0.09 DRAFT
@set VERSION 2.2 Beta
@set UPDATED 28 Aug 1999
@set ISBN 1-882114-53-1

@ifinfo
This file documents the GNU C library.

This is Edition @value{EDITION}, last updated @value{UPDATED},
of @cite{The GNU C Library Reference Manual}, for Version @value{VERSION}.

Copyright (C) 1993, '94, '95, '96, '97, '98, '99 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
section entitled ``GNU Library General Public License'' is included
exactly as in the original, and provided that the entire resulting
derived work is distributed under the terms of a permission notice
identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that the text of the translation of the section entitled ``GNU
Library General Public License'' must be approved for accuracy by the
Foundation.
@end ifinfo

@iftex
@shorttitlepage The GNU C Library Reference Manual
@end iftex
@titlepage
@center @titlefont{The GNU C Library}
@sp 1
@center @titlefont{Reference Manual}
@sp 2
@center Sandra Loosemore
@center with
@center Richard M. Stallman, Roland McGrath, Andrew Oram, and Ulrich Drepper
@sp 3
@center Edition @value{EDITION}
@sp 1
@center last updated @value{UPDATED}
@sp 1
@center for version @value{VERSION}
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1993, '94, '95, '96, '97, '98 Free Software Foundation, Inc.
@sp 2
Published by the Free Software Foundation @*
59 Temple Place -- Suite 330, @*
Boston, MA 02111-1307 USA @*
Printed copies are available for $50 each. @*
ISBN @value{ISBN} @*

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
section entitled ``GNU Library General Public License'' is included
exactly as in the original, and provided that the entire resulting
derived work is distributed under the terms of a permission notice
identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that the text of the translation of the section entitled ``GNU
Library General Public License'' must be approved for accuracy by the
Foundation.
@end titlepage
@page

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Main Menu
This is Edition @value{EDITION}, last updated @value{UPDATED}, of
@cite{The GNU C Library Reference Manual}, for Version @value{VERSION}
of the GNU C Library.
@end ifnottex

@include top-menu.texi
@include chapters.texi

@set lgpl-appendix
@node Copying, Concept Index, Contributors, Top
@include lgpl.texinfo


@node Concept Index, Type Index, Copying, Top
@unnumbered Concept Index

@printindex cp

@node Type Index, Function Index, Concept Index, Top
@unnumbered Type Index

@printindex tp

@node Function Index, Variable Index, Type Index, Top
@unnumbered Function and Macro Index

@printindex fn

@node Variable Index, File Index, Function Index, Top
@unnumbered Variable and Constant Macro Index

@printindex vr

@node File Index, , Variable Index, Top
@unnumbered Program and File Index

@printindex pg


@shortcontents
@contents
@bye
