ifeq ($(subdir),misc)
sysdep_routines += mips16-syscall0 mips16-syscall1 mips16-syscall2
sysdep_routines += mips16-syscall3 mips16-syscall4 mips16-syscall5
sysdep_routines += mips16-syscall6 mips16-syscall7
CFLAGS-mips16-syscall0.c += -fexceptions
CFLAGS-mips16-syscall1.c += -fexceptions
CFLAGS-mips16-syscall2.c += -fexceptions
CFLAGS-mips16-syscall3.c += -fexceptions
CFLAGS-mips16-syscall4.c += -fexceptions
CFLAGS-mips16-syscall5.c += -fexceptions
CFLAGS-mips16-syscall6.c += -fexceptions
CFLAGS-mips16-syscall7.c += -fexceptions
endif
