/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>
#include <rpc/xdr.h>
#include <rpcsvc/nis.h>

#include "nis_xdr.h"
#include "nis_cache2.h"


bool_t
xdr_fs_result(XDR *xdrs, fs_result *objp)
{
	 if (!_xdr_nis_error(xdrs, &objp->status)) {
		 return FALSE;
	 }
	 if (!xdr_long(xdrs, &objp->class)) {
		 return FALSE;
	 }
	 if (!xdr_bytes(xdrs, (char **)&objp->dir_data.dir_data_val, (u_int *)&objp->dir_data.dir_data_len, ~0)) {
		 return FALSE;
	 }
	 if (!xdr_long(xdrs, &objp->server_used)) {
		 return FALSE;
	 }
	 if (!xdr_long(xdrs, &objp->current_ep)) {
		 return FALSE;
	 }
	return TRUE;
}

bool_t
xdr_fs_request(XDR *xdrs, fs_request *objp)
{
	 if (!_xdr_nis_name(xdrs, &objp->name)) {
		 return FALSE;
	 }
	 if (!xdr_long(xdrs, &objp->old_class)) {
		 return FALSE;
	 }
	return TRUE;
}
