/* Generated by GNU locale 0.1.
   Copyright (C) 1995 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  */

#include "localeinfo.h"

const struct locale_data _nl_C_LC_MESSAGES =
{
  NULL, 0, /* no file mapped */
  4,
  {
    "[yY][[:alpha:]]",
    "[nN][[:alpha:]]",
    "",
    ""
  }
};
